### ISSUE TITLE
Film and Games Sites Suggestions

### ISSUE THREAD

**Issue by MetaApo13** [rippedpiracy/docs#13]
[Crackhub](crackhub.site)-Good for games and scene releases
[YTS](yts.mx)-Well desgined and easy to use. Recently clickbaits and pop-ups have become common, so annoying.
[The Ambassador](Ambassadorddl.site)-Direct Download Site with links to Gdrive files and other file hosting services. VPN not required. Password and username required for access to Google Drive files. This can be obtained by joining their Discord.
[Torlock](https://www.torlock.cc)-Software and movies.

**Comment by kekkodance** [comment]
you seem to have not even read what is on the site already, as crackhub is inside already. we will not include YTS for it's trash encodes, also the fact that it's impostors now, the real group is gone. since The Ambassador requires you to join a Discord server to get access to content, we won't include it.
