### ISSUE TITLE
Absolute respect

### ISSUE THREAD

**Issue by Alex123310** [rippedpiracy/docs#41]
Im just here to pay respect to all the people that loved this server and all the admins that put their souls in this server i am really sorry this just happened out of the blue there will never be a server like ripped with a "community" so good it was nice just to hang out in off topic not even asking for stuff you brought me a long way with a little kickstart from just being dumb and going on igg filling my pc with spyware and if anything happens of this server you an count me in! even if it has nothing to do with piracy!

**Comment by Alex123310** [comment]
ps i likely have not been banned from my disord acount  but i will keep an eye out as i dont know if fate will come from the tos gods

**Comment by Alex123310** [comment]
![image](https://user-images.githubusercontent.com/76629434/181770215-3c91ff66-6747-4318-bb53-7f035aedae1c.png)

**Comment by farawaycamera87** [comment]
> Im just here to pay respect to all the people that loved this server and all the admins that put their souls in this server i am really sorry this just happened out of the blue there will never be a server like ripped with a "community" so good it was nice just to hang out in off topic not even asking for stuff you brought me a long way with a little kickstart from just being dumb and going on igg filling my pc with spyware and if anything happens of this server you an count me in! even if it has nothing to do with piracy!

Same i was using steamunlocked back then then my friend told me its filled with malware and stopped using it then he got invited in a private tracker by his cousin and he gave me some torrents then i only asked him for torrents but he would  almost everytime say no so i decided to do the thing myself and i searched up things about piracy and things then i searched discord servers and i found the invite from dishboard i tought that it was a good server and i joined i was surprised by all the things they had i was just expecting a chat about piracy and a little list of games thay had but they had a damn site mirroring piracy sites i decided to use 1337x.to but then kekko reccomended me cs.rin.ru and online-fix.me i was a little dumb about it because i didn't know how to search up games and things but now i know 

-Cocolino
