### ISSUE TITLE
New browser that helps bypass website blocks

### ISSUE THREAD

**Issue by MeatHak** [rippedpiracy/docs#84]
https://mullvad.net/en/browser
It has been made in collaboration with Mullvad VPN (a very trustworthy VPN company) and the Tor Project (known for making and developing the Tor Browser)

You can read the info in the link i sent for more information.

**Comment by kekkodance** [comment]
We're not sure how we'd integrate this in the guide, it's just a firefox fork similar to LibreWolf which was recently made. We're adding projects that existed for a certain amount of time rather than getting all the bleeding edge (possibly discontinued in the future) tools. The same amount of "protection" can be achieved with Mullvad (which is paid) and it's extension.
